apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c7i0e1cwp-python
  janus-idp.io/tekton: c7i0e1cwp-python
  backstage.io/kubernetes-id: c7i0e1cwp-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c7i0e1cwp-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
